name: "pract-microserv-first-pass"

services:
  app:
    image: "local/pract-microserv-experim/first-pass"
    container_name: "pract-microserv-video-tuto-app"
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    depends_on:
      db:
        condition: service_healthy
      message-db:
        condition: service_healthy

  db:
    image: postgres:17
    container_name: "pract-microserv-video-tuto-db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: practical_microservices
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  message-db:
    image: ethangarofolo/message-db:1.3.1
    container_name: "pract-microserv-video-tuto-message-db"
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5